# Generated by Django 3.0.5 on 2020-04-26 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.IntegerField(choices=[(1, 'Father'), (2, 'Mother'), (3, 'Grand Father'), (4, 'Grand Mother'), (5, 'Brother'), (6, 'Sister'), (7, 'Son'), (8, 'Daughter'), (9, 'Husband'), (10, 'Wife'), (11, 'Uncle'), (12, 'Aunty')])),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='Person.Person')),
                ('related_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_person', to='Person.Person', verbose_name='Related Person')),
            ],
            options={
                'verbose_name_plural': 'Relationships',
            },
        ),
    ]
