# Generated by Django 3.0.5 on 2020-04-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('num', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Number')),
                ('first_name', models.CharField(max_length=15, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=15, verbose_name='Last Name')),
                ('phone_number', models.BigIntegerField(verbose_name='Contact Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('sex', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], verbose_name='Gender')),
            ],
            options={
                'verbose_name_plural': 'Person',
            },
        ),
    ]
